baseURL: "https://dylanj.xyz/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: dylanj.xyz
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Archives
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Projects
                  url: projects/
                - name: Tags
                  url: tags
                  weight: 10
                # - name: WiKi
                #   url: https://github.com/adityatelange/hugo-PaperMod/wiki/
                # - name: Discord
                #   url: https://discord.gg/ahpmTvhVmp

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Dylan R. Johnston's Blog"
    author: Dylan R. Johnston
    pygmentsUseClasses: true
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: false
    images: ["https://avatars.githubusercontent.com/u/5708800?v=4"]

    profileMode:
        enabled: true
        title: "Hi there 👋" # optional default will be site title
        subtitle: "Welcome to my blog"
        imageUrl: "https://avatars.githubusercontent.com/u/5708800?v=4" # optional
        imageTitle: "<title of image as alt>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
          - name: Archives
            url: "/archives"
          - name: Search
            url: "/search"
          - name: Projects
            url: /projects

    socialIcons: # optional
      - name: "github"
        url: "https://github.com/DylanRJohnston"
      - name: "linkedin"
        url: "https://www.linkedin.com/in/dylanrjohnston/"

    editPost:
        URL: "https://github.com/dylanrjohnston/dylanrjohnston.github.io/tree/master/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true 
    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]
pygmentsUseClasses: true
pygmentsCodefences: true
markup:
    highlight:
      codeFences: true
      guessSyntax: true
      hl_lines: ""
      lineNoStart: 1
      lineNos: false
      lineNumbersInTable: true
      tabWidth: 2
      noClasses: false
      style: monokai 

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
